### ISSUE TITLE
Conversion of Paylod failing on bootstrap

### ISSUE THREAD

**Issue by alinecmrgdaki** [Unleash/unleash_proxy_client_flutter#48]
### Describe the bug

Hello!

We got this error in our observability tool, it says 'cab', but reproducing locally I could confirm that it is in fact 'Payload'.

When passing Payload to Variant in bootstrap the `stringifyToggles` function throws `Converting object to an encodable object failed: Instance of 'Payload'`.

### Steps to reproduce the bug

1. Set a bootstrap to the SDK
2. Use a Payload inside a Variant on the bootstrap

### Expected behavior

I'd expect the SDK to bootstrap without errors even when passing Payloads to Variants.

### Logs, error output, etc.

```bash
Converting object to an encodable object failed: Instance of 'cab'
#0 _JsonStringifier.writeObject (third_party/dart/sdk/lib/convert/json.dart:793)
#1 _JsonStringifier.writeMap (third_party/dart/sdk/lib/convert/json.dart:874)
#2 _JsonStringifier.writeJsonValue (third_party/dart/sdk/lib/convert/json.dart:829)
#3 _JsonStringifier.writeObject (third_party/dart/sdk/lib/convert/json.dart:784)
#4 _JsonStringifier.writeMap (third_party/dart/sdk/lib/convert/json.dart:874)
#5 _JsonStringifier.writeJsonValue (third_party/dart/sdk/lib/convert/json.dart:829)
#6 _JsonStringifier.writeObject (third_party/dart/sdk/lib/convert/json.dart:784)
#7 _JsonStringifier.writeList (third_party/dart/sdk/lib/convert/json.dart:844)
#8 _JsonStringifier.writeJsonValue (third_party/dart/sdk/lib/convert/json.dart:823)
#9 _JsonStringifier.writeObject (third_party/dart/sdk/lib/convert/json.dart:784)
#10 _JsonStringifier.writeMap (third_party/dart/sdk/lib/convert/json.dart:874)
#11 _JsonStringifier.writeJsonValue (third_party/dart/sdk/lib/convert/json.dart:829)
#12 _JsonStringifier.writeObject (third_party/dart/sdk/lib/convert/json.dart:784)
#13 _JsonStringStringifier.printOn (third_party/dart/sdk/lib/convert/json.dart:982)
#14 _JsonStringStringifier.stringify (third_party/dart/sdk/lib/convert/json.dart:967)
#15 JsonEncoder.convert (third_party/dart/sdk/lib/convert/json.dart:345)
#15 stringifyToggles (/Users/runner/.pub-cache/hosted/pub.dev/unleash_proxy_client_flutter-1.4.0/lib/parse_stringify_toggles.dart:26)
#16 UnleashClient._init (/Users/runner/.pub-cache/hosted/pub.dev/unleash_proxy_client_flutter-1.4.0/lib/unleash_proxy_client_flutter.dart:175)
```
```


### Screenshots

_No response_

### Additional context

_No response_

### Unleash version

5.6.10

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

1.4.0

**Comment by kwasniew** [comment]
Thanks for a detailed report @alinecmrgdaki We identified the issue and will be submitting a patch today.

**Comment by kwasniew** [comment]
Hey! Please update to 1.5.3 and let us know if it fixed your problem
